services:
  - type: web
    name: revv-backend
    env: node
    plan: starter
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
